# ❌ YARN IS FORBIDDEN FOR THIS PROJECT
# 
# This FiveM loading screen DOES NOT WORK with Yarn!
# Yarn breaks FiveM resource loading.
#
# ✅ USE NPM ONLY:
#    npm install
#    npm run build
#
# If you see this file, DO NOT use yarn!
# The preinstall script will block yarn anyway.

nodeLinker: node-modules

# This file exists only to warn users - yarn is blocked in package.json
